[nodeul_programs]
title = "노들섬 ─ 프로그램"
url = "https://nodeul.org/programs/"
entrySelector = "div.list_warp.row-small.col-small div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.thumbnail-box"
waitUntil = "networkidle"

[nodeul_program]
title = "노들섬 ─ 프로그램 ─ 전체"
url = "https://nodeul.org/program/"
entrySelector = "div.row-small.col-small div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_show]
title = "노들섬 ─ 프로그램 ─ 전체 ─ 공연"
url = "https://nodeul.org/types/show/"
entrySelector = "div.row-small.col-small div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_festival]
title = "노들섬 ─ 프로그램 ─ 전체 ─ 페스티벌"
url = "https://nodeul.org/types/festival/"
entrySelector = "div.row-small.col-small div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_exhibit]
title = "노들섬 ─ 프로그램 ─ 전체 ─ 전시"
url = "https://nodeul.org/types/exhibit/"
entrySelector = "div.row-small.col-small div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_workshop]
title = "노들섬 ─ 프로그램 ─ 전체 ─ 위크숍"
url = "https://nodeul.org/types/workshop/"
entrySelector = "div.row-small.col-small div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_etc]
title = "노들섬 ─ 프로그램 ─ 전체 ─ 기타"
url = "https://nodeul.org/types/etc/"
entrySelector = "div.row-small.col-small div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-planned]
title = "노들섬 ─ 프로그램 ─ 예정"
url = "https://nodeul.org/program-planned/"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-planned_show]
title = "노들섬 ─ 프로그램 ─ 예정 ─ 공연"
url = "https://nodeul.org/program-planned/#show"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-planned_festival]
title = "노들섬 ─ 프로그램 ─ 예정 ─ 페스티벌"
url = "https://nodeul.org/program-planned/#festival"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-planned_exhibit]
title = "노들섬 ─ 프로그램 ─ 예정 ─ 전시"
url = "https://nodeul.org/program-planned/#exhibit"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-planned_workshop]
title = "노들섬 ─ 프로그램 ─ 예정 ─ 위크숍"
url = "https://nodeul.org/program-planned/#workshop"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-planned_etc]
title = "노들섬 ─ 프로그램 ─ 예정 ─ 기타"
url = "https://nodeul.org/program-planned/#etc"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-present]
title = "노들섬 ─ 프로그램 ─ 현재"
url = "https://nodeul.org/program-present/"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-present_show]
title = "노들섬 ─ 프로그램 ─ 현재 ─ 공연"
url = "https://nodeul.org/program-present/#show"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-present_festival]
title = "노들섬 ─ 프로그램 ─ 현재 ─ 페스티벌"
url = "https://nodeul.org/program-present/#festival"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-present_exhibit]
title = "노들섬 ─ 프로그램 ─ 현재 ─ 전시"
url = "https://nodeul.org/program-present/#exhibit"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-present_workshop]
title = "노들섬 ─ 프로그램 ─ 현재 ─ 워크숍"
url = "https://nodeul.org/program-present/#workshop"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_program-present_etc]
title = "노들섬 ─ 프로그램 ─ 현재 ─ 기타"
url = "https://nodeul.org/program-present/#etc"
entrySelector = "div.program-tab-content div.col-sm-3.col-xs-6"
titleSelector = "div.entry-title.ellipsis"
linkSelector = "div.matchbox article a"
contentSelector = "div.entry-meta.ellipsis span.date"
imageSelector = "div.entry-content-asset.m-program-asset img"
waitUntil = "networkidle"

[nodeul_linktree]
title = "노들섬 ─ 링크트리"
url = "https://linktr.ee/nodeul.seoul"
entrySelector = "div.sc-bdfBwQ.pkAuV"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[nodeulmusic_linktree]
title = "노들섬 음악노들 ─ 링크트리"
url = "https://linktr.ee/nodeul.music"
entrySelector = "div.sc-bdfBwQ.pkAuV"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[andtable_linktree]
title = "노들섬 앤테이블 ─ 링크트리"
url = "https://linktr.ee/nodeul.andtable"
entrySelector = "div[class='sc-bdfBwQ pkAuV'] div[class='sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 hqcxUx fbgZpG']"
titleSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh'] p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[space445_linktree]
title = "노들섬 아트스페이스 ─ 링크트리"
url = "https://linktr.ee/nodeul.space445"
entrySelector = "div[class='sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 fSUfbu kbFtjI']"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 CczVW rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[sikmuldo_linktree]
title = "노들섬 식물도 ─ 링크트리"
url = "https://linktr.ee/sikmuldo"
entrySelector = "div[class='sc-bdfBwQ pkAuV'] div[class='sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 hqcxUx hdlZPy']"
titleSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh'] p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 kVCYxL rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[book_linktree]
title = "노들서가 ─ 링크트리"
url = "https://linktr.ee/nodeulbook"
entrySelector = "div[class='sc-bdfBwQ pkAuV'] div[class='sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 jKJSbm bUvTfm']"
titleSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh'] p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 kkVeT rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"
