[andtable_linktree]
title = "노들섬 앤테이블 ─ 링크트리"
url = "https://linktr.ee/nodeul.andtable"
entrySelector = "div[class='sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 fSUfbu kbFtjI']"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 CczVW rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[space445_linktree]
title = "노들섬 아트스페이스 ─ 링크트리"
url = "https://linktr.ee/nodeul.space445"
entrySelector = "div[class='sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 fSUfbu kbFtjI']"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 CczVW rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[sikmuldo_linktree]
title = "노들섬 식물도 ─ 링크트리"
url = "https://linktr.ee/sikmuldo"
entrySelector = "div[class='sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 fSUfbu kbFtjI']"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 CczVW rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"

[book_linktree]
title = "노들서가 ─ 링크트리"
url = "https://linktr.ee/nodeulbook"
entrySelector = "div[class='sc-bdfBwQ StyledContainer__StyledLinkContainer-sc-1kae6sc-0 fSUfbu kbFtjI']"
titleSelector = "p[class='sc-hKgILt Button__StyledText-sc-uh5tyw-0 CczVW rsIfq']"
linkSelector = "a[class='sc-pFZIQ StyledButton-sc-686c3k-0 ldGKnQ dLjCyh']"